language: php

before_script:
  - chmod a+x ./tests/install-php-extension.sh
  - ./tests/install-php-extension.sh
  - composer self-update
  - composer update --dev

php:
  - 5.4
  - 5.5

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src
  - phpunit --configuration ./phpunit.xml.dist
