language: php

php:
  - 5.4
  - 5.5

before_script:
  - chmod a+x ./tests/install-php-extension.sh
  - chmod a+x ./tests/install-php-apcu.sh
  - ./tests/install-php-apcu.sh
  - ./tests/install-php-extension.sh
  - phpenv config-add tests/$TRAVIS_PHP_VERSION.ini
  - phpenv config-add tests/apc.ini
  - composer self-update
  - composer update --dev


script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src
  - phpunit --configuration ./phpunit.xml.dist
